# Generated by Django 2.1 on 2019-02-06 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter your Instagram username', max_length=200)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish')),
                ('text', models.TextField()),
                ('title', models.CharField(default='', help_text='Title or Subject of Post', max_length=100)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('ext_author', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.IntegerField(choices=[(0, 'Local Post'), (1, 'Blog'), (2, 'Podcast'), (3, 'News')], default=0)),
                ('ext_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter your Twitter username', max_length=200)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField(help_text="This sets up a short link to the page e.g. 'my-group-name' results in http://yqnet.uk/my-group-name", max_length=200, unique=True)),
                ('redirect', models.URLField(blank=True, help_text='Instead of a dedicated page people will automatically be redirected to the provided url', null=True)),
                ('body', models.TextField(blank=True, default='')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XMLFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Url should be an Atom or RSS feed', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('source', models.IntegerField(choices=[(1, 'Blog'), (2, 'Podcast'), (3, 'News')])),
                ('manual_thumbnail', models.URLField(blank=True, help_text="Url to a thumbnail img, used if the feed doesn't provide one automatically", null=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='xml_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_yqn.XMLFeed'),
        ),
    ]
