# Generated by Django 2.1 on 2019-02-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0002_auto_20190207_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventslocation',
            old_name='group',
            new_name='user_page',
        ),
    ]
