# Generated by Django 2.1 on 2019-02-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0003_auto_20190207_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='post_code',
        ),
        migrations.AlterField(
            model_name='venue',
            name='lat_lng',
            field=models.CharField(help_text='Can be looked up from valid UK postcode', max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='postcode',
            field=models.CharField(help_text='Must be valid UK postcode', max_length=20),
        ),
        migrations.AlterField(
            model_name='venue',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
