# Generated by Django 2.1 on 2019-02-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0005_auto_20190214_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
