# Generated by Django 2.1 on 2019-02-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0007_auto_20190215_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventslocation',
            old_name='user_page',
            new_name='group_page',
        ),
    ]
