# Generated by Django 2.1 on 2019-02-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0008_auto_20190215_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='lat',
            field=models.FloatField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='lng',
            field=models.FloatField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
