# Generated by Django 2.1 on 2019-02-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0010_remove_venue_lat_lng'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarFeed',
        ),
        migrations.AddField(
            model_name='event',
            name='private',
            field=models.BooleanField(default=False, help_text='Only show this event to logged in users'),
        ),
        migrations.AddField(
            model_name='eventslocation',
            name='private',
            field=models.BooleanField(default=False, help_text='Only show this information to logged in users'),
        ),
        migrations.AddField(
            model_name='post',
            name='private',
            field=models.BooleanField(default=False, help_text='Only show this post to logged in users'),
        ),
    ]
