# Generated by Django 2.1 on 2019-02-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0012_grouppagemedia_usermedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppagemedia',
            name='file_upload',
            field=models.FileField(upload_to='pages/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='file_upload',
            field=models.FileField(upload_to='user/%Y/%m/%d'),
        ),
    ]
