# Generated by Django 2.1 on 2019-02-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0013_auto_20190225_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(blank=True, help_text='If left blank enquieries will be forwarded to your current login email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='eventslocation',
            name='email',
            field=models.EmailField(blank=True, help_text='If left blank enquiries will be forwarded to your current login email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='grouppage',
            name='email',
            field=models.EmailField(default='', help_text='Email address for enquiries', max_length=254),
            preserve_default=False,
        ),
    ]
