# Generated by Django 2.1 on 2019-02-28 09:57

import db_yqn.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0014_auto_20190227_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for enquiries', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='grouppage',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for enquiries', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='grouppage',
            name='slug',
            field=models.SlugField(help_text="This sets up a short link to the page e.g. 'my-group-name' results in http://yqnet.uk/my-group-name", max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid'), db_yqn.models.validate_no_slug_clash]),
        ),
    ]
