# Generated by Django 2.1 on 2019-03-04 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_yqn', '0015_auto_20190228_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppage',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='page_updater', to=settings.AUTH_USER_MODEL),
        ),
    ]
