# Generated by Django 2.1 on 2019-03-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0018_auto_20190325_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter',
            name='username',
            field=models.CharField(help_text='Enter your Twitter username', max_length=200, unique=True),
        ),
    ]
