# Generated by Django 2.1 on 2019-03-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('db_yqn', '0020_auto_20190326_0055'), ('db_yqn', '0021_auto_20190327_1615'), ('db_yqn', '0022_auto_20190327_1626'), ('db_yqn', '0023_auto_20190327_1632')]

    dependencies = [
        ('db_yqn', '0019_auto_20190325_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_yqn.Venue', verbose_name='Venue name'),
        ),
        migrations.AlterField(
            model_name='eventslocation',
            name='url',
            field=models.URLField(blank=True, help_text='Link to find out about your events', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Venue name'),
        ),
        migrations.AlterField(
            model_name='eventslocation',
            name='group_page',
            field=models.ForeignKey(help_text='Link to a group page', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db_yqn.GroupPage'),
        ),
        migrations.AlterField(
            model_name='eventslocation',
            name='title',
            field=models.CharField(help_text='e.g. Quaker Meeting', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventslocation',
            name='url',
            field=models.URLField(blank=True, help_text='External link to find out more about your events', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_yqn.UserMedia'),
        ),
    ]
