# Generated by Django 2.1 on 2019-03-29 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0020_auto_20190326_0055_squashed_0023_auto_20190327_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_yqn.UserMedia'),
        ),
    ]
