# Generated by Django 2.1 on 2019-03-29 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0021_auto_20190329_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Area name')),
                ('lat_tl', models.FloatField(max_length=200)),
                ('lng_tl', models.FloatField(max_length=200)),
                ('lat_br', models.FloatField(max_length=200)),
                ('lng_br', models.FloatField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='eventslocation',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_yqn.Venue', verbose_name='Venue name'),
        ),
    ]
