# Generated by Django 2.1 on 2019-04-04 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('db_yqn', '0023_auto_20190402_1414'), ('db_yqn', '0024_auto_20190404_1306'), ('db_yqn', '0025_auto_20190404_2131')]

    dependencies = [
        ('db_yqn', '0022_auto_20190329_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Region name')),
                ('lat_tl', models.FloatField(max_length=200, verbose_name='Latitude top left')),
                ('lng_tl', models.FloatField(max_length=200, verbose_name='Longitude top left')),
                ('lat_br', models.FloatField(max_length=200, verbose_name='Latitude bottom right')),
                ('lng_br', models.FloatField(max_length=200, verbose_name='Longitude bottom right')),
            ],
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(help_text='e.g. Westminster Quaker Meeting', on_delete=django.db.models.deletion.CASCADE, to='db_yqn.Venue', verbose_name='Venue name'),
        ),
        migrations.AlterField(
            model_name='eventslocation',
            name='venue',
            field=models.ForeignKey(help_text='Lookup an existing venue or Add new', on_delete=django.db.models.deletion.CASCADE, to='db_yqn.Venue', verbose_name='Venue name'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='lat',
            field=models.FloatField(default=-99, max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='lng',
            field=models.FloatField(default=-99, max_length=200),
        ),
        migrations.AddField(
            model_name='eventslocation',
            name='region',
            field=models.ForeignKey(blank=True, help_text='If your events happen in multiple places in a Region rather than at a single Venue. e.g. London Area or Add new', null=True, on_delete=django.db.models.deletion.CASCADE, to='db_yqn.Region'),
        ),
        migrations.AlterField(
            model_name='eventslocation',
            name='group_page',
            field=models.ForeignKey(help_text='Link to a Group page or Add new', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db_yqn.GroupPage'),
        ),
        migrations.AlterField(
            model_name='eventslocation',
            name='url',
            field=models.URLField(blank=True, help_text='External link to find out more about your events. e.g. http://example.com/events', null=True, verbose_name='Link (URL)'),
        ),
        migrations.AlterField(
            model_name='eventslocation',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Lookup an existing Venue or Add new', null=True, on_delete=django.db.models.deletion.CASCADE, to='db_yqn.Venue', verbose_name='Venue name'),
        ),
        migrations.AlterField(
            model_name='xmlfeed',
            name='url',
            field=models.URLField(help_text='Url should be an Atom or RSS feed', unique=True, verbose_name='Link (URL)'),
        ),
    ]
