# Generated by Django 2.1 on 2019-05-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0024_post_comments_squashed_0028_auto_20190409_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group_page',
            field=models.ForeignKey(help_text='Associate this Event with a Group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db_yqn.GroupPage'),
        ),
        migrations.AlterField(
            model_name='eventslocation',
            name='group_page',
            field=models.ForeignKey(help_text='Associate this event with a Group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db_yqn.GroupPage'),
        ),
        migrations.AlterField(
            model_name='grouppage',
            name='redirect',
            field=models.URLField(blank=True, help_text='Provide a Link to redirect people to your website', null=True, verbose_name='Link'),
        ),
    ]
