# Generated by Django 2.1 on 2019-05-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0025_auto_20190501_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppage',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for enquiries (public)', max_length=254, null=True),
        ),
    ]
