# Generated by Django 2.1 on 2019-05-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0026_auto_20190502_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, help_text='Optional link for people to find out more', null=True, verbose_name='Link (URL)'),
        ),
    ]
