# Generated by Django 2.2 on 2019-05-23 12:25

import db_yqn.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('db_yqn', '0027_auto_20190505_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppage',
            name='slug',
            field=models.SlugField(help_text="This sets up a short link to the page e.g. 'my-group-name' results in https://quakr.net/my-group-name", max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid'), db_yqn.models.validate_no_slug_clash]),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_post'),
        ),
    ]
